add python module check script, working on live query rsid

diff --git a/src/env_check b/src/env_check
--- a/src/env_check
+++ b/src/env_check
@@ -61,10 +61,13 @@ checked=''
 self="$(echo "$0" | sed -e 's,.*/,,')"
 cmdlist='httpd python3 pip psql php'
 apache_mod='mod_wsgi'
+pymod_check='module_check.py'
 
 # functions
 usage() {
-  printf 'Usage:\n\t\033[1m%s\033[0m [\033[1m-h|-?|--help\033[0m] [\033[1m-S|--system\033[0m \033[4mos_name\033[0m]\n' "$self"
+  printf "Usage:\n\t\033[1m%s\033[0m [\033[1m-h|-?|--help\033[0m] [\
+\033[1m-S|--system\033[0m \033[4mos_name\033[0m] [\033[1m--python\
+\033[0m \033[4mpath/to/py_script\033[0m]\n" "$self"
 }
 die() {
   printf '\033[1m%s\033[0m\n' "$1" >&2
@@ -96,6 +99,18 @@ while :; do
 	    system=${1#*=};;
 	  --system=)
 	    die 'ERROR: "--system" requires a non-empty option argument.';;
+	  --python)
+	    if [ "$2" ]; then
+	      pymod_check=$2
+	      shift
+	    else
+	      die 'ERROR: "--python" requires a file path for the python check modules script.'
+	    fi
+	    ;;
+	  --python=?*)
+	    system=${1#*=};;
+	  --python=)
+	    die 'ERROR: "--python" requires a file path for the python check modules script.';;
 	  --)
 	    shift
 	    break;;
@@ -169,12 +184,20 @@ else
   printf '\033[1mERROR: Unable to check enabled apache server modules, apache http server not found.\033[0m\n'
 fi
 
-# Check if python version is high enough
+# Check if python version is high enough and check existence of required python modules
 if echo "$checked" | grep -q 'python3'
 then
   if python3 --version | grep -q '3\.[7-9]\|3\.[1-9]\+[0-9]\+'
   then
     printf "\033[0mPython3 version met the minimum requirement\n"
+    printf "\033[0mChecking python modules...\n"
+    python3 $pymod_check
+    exit_code=$?
+    if [ $exit_code -ne 0 ]
+    then
+      printf "\033[1mWARN: Python module check with exit code of %s. See above for debug.\033[0m\n" "$exit_code"
+      exit 1
+    fi
   else
     printf "\033[1mWARN: Python version is too low, you should upgrade Python to at least version 3.7\033[0m\n"
   fi
