Complete env_check script, needs update when new requirement is added

diff --git a/src/env_check b/src/env_check
--- a/src/env_check
+++ b/src/env_check
@@ -1,14 +1,36 @@
 #!/bin/sh
 
 # Detect OS
-if [ -f "/etc/os-release" ]
+if [ -f '/etc/os-release' ]
 then
-  OS="$(grep '^ID_LIKE=.*' '/etc/os-release')" || OS="$(grep '^ID=.*' '/etc/os-release')"
-elif [ ! -f "/etc/os-release" ]
+  os_release='/etc/os-release'
+elif [ -f '/usr/lib/os-release' ]
+then
+  os_release='/usr/lib/os-release'
+fi
+
+if [ -f "${os_release}" ]
+then
+  OS="$(grep '^ID_LIKE=.*' ${os_release} || grep '^ID=.*' ${os_release})"
+  OS="${OS#*=}"
+  OS="${OS#\"}"
+  OS="${OS%\"}"
+  OS="${OS#\'}"
+  OS="${OS%\'}"
+  OS="$(echo "$OS" | tr '[:upper:]' '[:lower:]')"
+elif [ ! -f "${os_release}" ]
 then
   OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
 fi
 case "$OS" in
+  fedora)
+    # Fedora, CentOS, RedHat ...
+    system='fedora'
+    ;;
+  debian)
+    # Debian, Ubuntu ...
+    system='debian'
+    ;;
   linux|gnu|gnu/*)
     # ...
     system='linux'
@@ -37,6 +59,8 @@ esac
 # Initialise variable
 checked=''
 self=`echo "$0" | sed -e 's,.*/,,'`
+cmdlist='python3 pip php httpd'
+apache_mod='mod_wsgi'
 
 # functions
 usage() {
@@ -46,6 +70,12 @@ die() {
   printf '\033[1m%s\033[0m\n' "$1" >&2
   exit 1
 }
+hand_check_info() {
+  printf "\033[0mInfo: Your OS is not in our predefined OS list, \
+Please manually check if \033[4m%s\033[0m is installed and the requ\
+ired apache module ( \033[4m%s\033[0m ) is enabled.\nInfo: Please a\
+lso noted that Python needs to have >=3.7 version\n" "$cmdlist" "$apache_mod"
+}
 
 # get options
 while :; do
@@ -54,52 +84,58 @@ while :; do
 	    usage
 	    exit
 	    ;;
-		-S|--system)
-			if [ "$2" ]; then
-				system=$2
-				shift
-			else
-				die 'ERROR: "-S" or "--system" requires a non-empty option argument.'
-			fi
-			;;
-		--system=?*)
-			system=${1#*=};;
-		--system=)
-			die 'ERROR: "--system" requires a non-empty option argument.';;
-		--)
-			shift
-			break;;
-		-?*)
-			printf '\033[5mWARN: Unknown option (ignored): %s\033[0m\n%s\n' "$1" "$(usage)" >&2
-			exit 128;;
-		*)
-			break
+	  -S|--system)
+	    if [ "$2" ]; then
+	      system=$2
+	      shift
+	    else
+	      die 'ERROR: "-S" or "--system" requires a non-empty option argument.'
+	    fi
+	    ;;
+	  --system=?*)
+	    system=${1#*=};;
+	  --system=)
+	    die 'ERROR: "--system" requires a non-empty option argument.';;
+	  --)
+	    shift
+	    break;;
+	  -?*)
+	    printf '\033[5m\033[1mWARN: Unknown option (ignored): %s\033[0m\n%s\n' "$1" "$(usage)" >&2
+	    exit 128;;
+	  *)
+	    break
 	esac
 
+  shift
 done
 if test $# != 0; then
   printf "\033[5m\033[1m$self: too many arguments\033[0m\n%s\n" "$(usage)" >&2
   exit 1
 fi
 
+system="$(echo "$system" | tr '[:upper:]' '[:lower:]')"
 case "$system" in
-  "macOS"|"darwin")
+  "macos"|"darwin")
     cmdlist='python3 pip php httpd'
     apache_mod='mod_wsgi';;
-  "Ubuntu"|"Debian")
+  "fedora"|"centos"|"redhat"|"oracle")
+    cmdlist='python3 pip php httpd'
+    apache_mod='mod_wsgi';;
+  "ubuntu"|"debian")
     cmdlist='python3 pip php apache2'
     apache_mod='mod_wsgi';;
   "freebsd")
-    printf '\033[1mWARN: Your OS is freebsd. Compatibility is not tested on this system!\033[0m\n'
+    printf '\033[1mWARN: Your OS is freebsd. Compatibility is not tested on this system!\033[0m\n%s\n' "$(hand_check_info)"
     exit 1
     ;;
-  "Windows"|"windows")
-    printf '\033[1mWARN: Your OS is Windows. Compatibility is not tested on this system!\033[0m\n'
+  "windows")
+    printf '\033[1mWARN: Your OS is Windows. Compatibility is not tested on this system!\033[0m\n%s\n' "$(hand_check_info)"
     exit 1
     ;;
   *)
-    cmdlist='python3 pip php httpd'
-    apache_mod='mod_wsgi';;
+    hand_check_info
+    exit 0
+    ;;
 esac
 
 ####### Main Program #######
@@ -125,11 +161,11 @@ then
     httpd_check="$(echo $mod_enable | grep $n)"
     if [ -z "$httpd_check" ]
     then
-      printf '\033[1mWARN: %s needs to be enabled\033[0m\n' "$n"
+      printf '\033[1mWARN: \033[4m%s\033[0m\033[1m needs to be enabled\033[0m\n' "$n"
     fi
   done
 else
-  printf '\033[1mERROR: unable to check enabled apache server modules, apache http server not found.\033[0m\n'
+  printf '\033[1mERROR: Unable to check enabled apache server modules, apache http server not found.\033[0m\n'
 fi
 
 # Check if python version is high enough
