minor description change in help

diff --git a/src/snp_query b/src/snp_query
--- a/src/snp_query
+++ b/src/snp_query
@@ -9,17 +9,17 @@ version=1.3
 # shipped with ability to query and export individual file.
 
 # Version 1.1
-# shipped with abiilty to query and export RSID marked SNP entry (with -r option)
+# shipped with ability to query and export RSID marked SNP entry (with -r option)
 
 # Version 1.0
 # shipped with ability to query and export private SNP ID entry.
 
 # Functions
 usage() {
-  printf '\n\033[1m\033[7mUsage:\033[0m\n%s [\033[1m-h\033[0m|\033[1m-\?\033[0m|\033[1m--help\033[0m] [\033[1m-r\033[0m|\033[1m--reverse\033[0m] [\033[1m-v\033[0m|\033[1m--version\033[0m] [\033[1m-s\033[0m|\033[1m--source\033[0m \033[4mpath/to/source\033[0m] [\033[1m-D\033[0m|\033[1m--destination\033[0m \033[4mpath/to/destination\033[0m] [\033[1m-f\033[0m|\033[1m--file\033[0m \033[4mpath/to/file\033[0m]\n\n\033[1m\033[7mArguments:\033[0m \n\t\033[1m-D\033[0m | \033[1m--destination\033[0m\tDestination directory. If not supplied, directory 'iid' under the source directory will be used or will be created (in case not exist). Space in the name should be escaped, see \033[1m-s\033[0m argument for more info.\n\t\033[1m-f\033[0m | \033[1m--file\033[0m\tSingle file mode. File with extension other than '.gt' is also accepted, however, it is important to include a file extension to prevent error. Input only a signle file insead of a directory.\n\t\033[1m-h\033[0m | \033[1m-\?\033[0m | \033[1m--help\033[0m\tDisplay usage.\n\t\033[1m-r\033[0m | \033[1m--reverse\033[0m\033[0m\tReverse mode. The script will export rsid records instead of private id records. Can be combined with single file mode.\n\t\033[1m-s\033[0m | \033[1m--source\033[0m\tSource Directory. If not supplied, current working directory will be used. In case directory name contain space, it should be escaped with double quote (\"\") or (\\ ).\n\t\033[1m-v\033[0m | \033[1m--version\033[0m\tPrint script version.\n' "$0"
+  printf '\n\033[1m\033[7mUsage:\033[0m\n%s [\033[1m-h\033[0m|\033[1m-\?\033[0m|\033[1m--help\033[0m] [\033[1m-r\033[0m|\033[1m--reverse\033[0m] [\033[1m-v\033[0m|\033[1m--version\033[0m] [\033[1m-s\033[0m|\033[1m--source\033[0m \033[4mpath/to/source\033[0m] [\033[1m-D\033[0m|\033[1m--destination\033[0m \033[4mpath/to/destination\033[0m] [\033[1m-f\033[0m|\033[1m--file\033[0m \033[4mpath/to/file\033[0m]\n\n\033[1m\033[7mArguments:\033[0m \n\t\033[1m-D\033[0m | \033[1m--destination\033[0m\tDestination directory. If not supplied, directory \033[4miid\033[0m under the source directory will be used or will be created (in case not exist). Space in the name should be escaped, see \033[1m-s\033[0m argument for more info.\n\t\033[1m-f\033[0m | \033[1m--file\033[0m\tSingle file mode. File with extension other than '.gt' is also accepted, however, it is important to include a file extension to prevent error. Input only a signle file insead of a directory.\n\t\033[1m-h\033[0m | \033[1m-\?\033[0m | \033[1m--help\033[0m\tDisplay usage.\n\t\033[1m-r\033[0m | \033[1m--reverse\033[0m\033[0m\tReverse mode. The script will export rsid records instead of private id records. Can be combined with single file mode.\n\t\033[1m-s\033[0m | \033[1m--source\033[0m\tSource Directory. If not supplied, current working directory will be used. In case directory name contain space, it should be escaped with double quote (\"\") or (\\ ).\n\t\033[1m-v\033[0m | \033[1m--version\033[0m\tPrint script version.\n' "$0"
 }
 die() {
-  printf '%s\n' "$1" >&2
+  printf '\033[1m%s\033[0m\n' "$1" >&2
   exit 1
 }
 checksource() {
@@ -58,7 +58,7 @@ while :; do
         file=$2
         shift
       else
-        die '\033[1mERROR: "-f or --file" requires a non-empty option argument.\033[0m'
+        die 'ERROR: "-f" or "--file" requires a non-empty option argument.'
       fi
       ;;
     --file=?*)
@@ -67,14 +67,14 @@ while :; do
       ;;
     # Handle the case of an empty --file=
     --file=)
-      die '\033[1mERROR: "--file" requires a non-empty option argument.\033[0m'
+      die 'ERROR: "--file" requires a non-empty option argument.'
       ;;
     -s|--source)
       if [ "$2" ]; then
         sc_dir=$2
         shift
       else
-        die '\033[1mERROR: "-s or --source" requires a non-empty option argument.\033[0m'
+        die 'ERROR: "-s" or "--source" requires a non-empty option argument.'
       fi
       ;;
     --source=?*)
@@ -83,14 +83,14 @@ while :; do
       ;;
     # Handle the case of an empty --source=
     --source=)
-      die '\033[1mERROR: "--source" requires a non-empty option argument.\033[0m'
+      die 'ERROR: "--source" requires a non-empty option argument.'
       ;;
     -D|--destination)
       if [ "$2" ]; then
         des_dir=$2
         shift
       else
-        die '\033[1mERROR: "-D or --destination" requires a non-empty option argument.\033[0m'
+        die 'ERROR: "-D" or "--destination" requires a non-empty option argument.'
       fi
       ;;
     --destination=?*)
@@ -99,7 +99,7 @@ while :; do
       ;;
     # Handle the case of an empty --destination=
     --destination=)
-      die '\033[1mERROR: "--destination" requires a non-empty option argument.\0330m'
+      die 'ERROR: "--destination" requires a non-empty option argument.'
       ;;
     # -V|--verbose)
     #   verbose=$((verbose + 1))  # Each -v adds 1 to verbosity.
@@ -176,7 +176,7 @@ then
 		do
        		 	printf 'Reading %s\n' "$n"
        		 	m="${des_dir}/${n%.gt}_iid.gt"
-	        	cat "$n" | grep -v '\(\(^rs[0-9]\+.*\)\|\(^#.*\)\)' > "$m"
+	        	grep -v '\(\(^rs[0-9]\+.*\)\|\(^#.*\)\)' "$n" > "$m"
        		 	printf 'Finished with %s, output written in %s\n' "$n" "$m"
 		done
 	elif [ "$reverse" = true ]
@@ -187,7 +187,7 @@ then
 		do
 			printf 'Reading %s\n' "$n"
        		 	m="${des_dir}/${n%.gt}_rsid.gt"
-			cat "$n" | grep '\(\(^rs[0-9]\+.*\)\)' > "$m"
+			grep '\(\(^rs[0-9]\+.*\)\)' "$n" > "$m"
 			printf 'Finished with %s, output written in %s\n' "$n" "$m"
 		done
 	fi
@@ -203,14 +203,14 @@ else
 		# export rsid
 			printf 'Reading %s\n' "${file}"
       m="${des_dir}/${f%.*}_rsid.gt"
-			cat "$file" | grep '\(\(^rs[0-9]\+.*\)\)' > "$m"
+			grep '\(\(^rs[0-9]\+.*\)\)' "$file" > "$m"
 			printf 'Finished with %s, output written in %s\n' "$f" "$m"
 	elif [ "$reverse" = false ]
 	then
 		# export iid
     printf 'Reading %s\n' "$file"
     m="${des_dir}/${f%.*}_iid.gt"
-    cat "$file" | grep -v '\(\(^rs[0-9]\+.*\)\|\(^#.*\)\)' > "$m"
+    grep -v '\(\(^rs[0-9]\+.*\)\|\(^#.*\)\)' "$file" > "$m"
     printf 'Finished with %s, output written in %s\n' "$f" "$m"
 	fi
 fi
